// Numerals
export const REQUEST_NUMERALS = 'REQUEST_NUMERALS'
export const SET_NUMERALS = 'SET_NUMERALS'
export const RECEIVE_NUMERALS = 'RECEIVE_NUMERALS'
export const FAIL_NUMERALS = 'FAIL_NUMERALS'
export const FIND_NUMERAL = 'FIND_NUMERAL'
export const SET_CURRENT_NUMERAL = 'SET_CURRENT_NUMERAL'

// UI
export const CLOSE_DETAILS = 'CLOSE_DETAILS'
export const OPEN_DETAILS = 'OPEN_DETAILS'
export const CURRENT_DETAILS = 'CURRENT_DETAILS'
