// Numerals
export const REQUEST_NUMERALS = 'REQUEST_NUMERALS';
export const SET_NUMERALS = 'SET_NUMERALS';
export const RECEIVE_NUMERALS = 'RECEIVE_NUMERALS';
export const FAIL_NUMERALS = 'FAIL_NUMERALS';
export const GOTO_NUMERAL_PAGE = 'GOTO_NUMERAL_PAGE';
export const NEXT_NUMERAL_PAGE = 'NEXT_NUMERAL_PAGE';
export const PREV_NUMERAL_PAGE = 'PREV_NUMERAL_PAGE';
export const SORT_NUMERALS = 'SORT_NUMERALS';
export const FILTER_NUMERALS = 'FILTER_NUMERALS';
