// Numerals
export const REQUEST_NUMERALS = 'REQUEST_NUMERALS';
export const SET_NUMERALS = 'SET_NUMERALS';
export const RECEIVE_NUMERALS = 'RECEIVE_NUMERALS';
export const FAIL_NUMERALS = 'FAIL_NUMERALS';
export const FIND_NUMERAL = 'FIND_NUMERAL';

// UI
export const TOGGLE_SEARCH = 'TOGGLE_SEARCH';
